### ISSUE TITLE
Add an app icon to the application.

### ISSUE THREAD

**Issue by aniketsen123** [aniketsen123/Mvvm_newsapp#1]
Add a creative app icon to the application

**Comment by pjyotianwar** [comment]
Hey @aniketsen123
I want to work on this issue under JWOC

**Comment by tusharsh21** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue please assign me this issue.

**Comment by aniketsen123** [comment]
Sure @Aniket-011

**Comment by aniketsen123** [comment]
@Aniket-011 your time is up

**Comment by realsh9dy** [comment]
Please assign me this issue.
