### ISSUE TITLE
Add a SplashScreen.

### ISSUE THREAD

**Issue by aniketsen123** [aniketsen123/Mvvm_newsapp#2]
Add a Splash Screen which will be shown for 2 seconds.

**Comment by pjyotianwar** [comment]
Hey @aniketsen123
I want to work on this issue under JWOC

**Comment by tusharsh21** [comment]
I want to work on this issue under JWOC

**Comment by realsh9dy** [comment]
Please assign me this issue

**Comment by aniketsen123** [comment]
sure @tusharsh21
