### ISSUE TITLE
A new UI update

### ISSUE THREAD

**Issue by Poras-oss** [aniketsen123/Mvvm_newsapp#5]
### UI UPDATE

Currently the layout of the RecyclerView list is very basic. I want to add a CardView to make it look more organised and beatiful.
I am interested in working on this feature under JWOC kindly assign me this issue so i can start working on it.
### I want to change it from this
<img src="https://user-images.githubusercontent.com/55978642/218838025-303b751e-32c9-43d7-84a3-5839bab1b071.jpeg" width="332" height="514" />

### To something like this
![Capture](https://user-images.githubusercontent.com/55978642/218838115-089460e3-bbcb-441d-b5a4-f191789bfa28.PNG)

**Comment by Arsh-78** [comment]
hey I would like to take up this issue could you please allot me this

**Comment by anandrajsingh** [comment]
Hey, @aniketsen123 can you assign this issue to me

**Comment by sarthaknerd** [comment]
hi can you assign me this issue i am android developer i would like to contribute and up-skill myself.

**Comment by aniketsen123** [comment]
@Poras-oss  your's time up.

**Comment by aniketsen123** [comment]
@Arsh-78 whiling to do this?

**Comment by Poras-oss** [comment]
@aniketsen123  I'll complete it by today. I was busy contributing on the project I was assigned first. Sorry for the delay🙏
